import { CarsModel } from "@/models/cars.model";

export const cars: CarsModel[] = [
  {
    id: "rana-1401-006",
    name: "رانا پلاس",
    model: "2022-1401",
    rental: {
      days_3_to_14: 1550000,
      more_than_14_days: 1450000,
      minimum_rental: 3,
      deposit: 23000000,
    },
    capacity: {
      passengers: 5,
      luggage: 3,
      door: 4,
    },
    features: {
      cruise_control: true,
      chassis_type: "سواری",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۴ اسپیکر",
      monitor: "۷ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.6,
      cylinders: 4,
      acceleration: 12.5,
      fuel_consumption: 6.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2000000,
      intercity_per_km: 12000,
      airport_transfer: 1300000,
    },
    img: "runa.png",
    location: "استان تهران",
    reviewCount: 57,
    ratingNumber: 4.3,
  },

  {
    id: "samand-soren-1401-011",
    name: "سمند سورن پلاس",
    model: "2022-1401",
    rental: {
      days_3_to_14: 1650000,
      more_than_14_days: 1550000,
      minimum_rental: 3,
      deposit: 24000000,
    },
    capacity: {
      passengers: 5,
      luggage: 3,
      door: 4,
    },
    features: {
      cruise_control: true,
      chassis_type: "سواری",
      option_type: "فول آپشن",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۴ اسپیکر",
      monitor: "۷ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.8,
      cylinders: 4,
      acceleration: 11.8,
      fuel_consumption: 7.4,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2000000,
      intercity_per_km: 12000,
      airport_transfer: 1300000,
    },
    img: "samand-lx.png",
    location: "استان تهران",
    reviewCount: 63,
    ratingNumber: 4.1,
  },

  {
    id: "peugeot-206-1400-012",
    name: "پژو ۲۰۶",
    model: "2021-1400",
    rental: {
      days_3_to_14: 1350000,
      more_than_14_days: 1250000,
      minimum_rental: 3,
      deposit: 21000000,
    },
    capacity: {
      passengers: 5,
      luggage: 2,
      door: 4,
    },
    features: {
      cruise_control: false,
      chassis_type: "هاچ‌بک",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.4,
      cylinders: 4,
      acceleration: 13.0,
      fuel_consumption: 6.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1800000,
      intercity_per_km: 11000,
      airport_transfer: 1200000,
    },
    img: "p206.png",
    location: "استان اصفهان",
    reviewCount: 48,
    ratingNumber: 4.0,
  },
  {
    id: "renault-l90-automatic-1400-001",
    name: "رنو ال ۹۰ اتوماتیک",
    model: "2022-1402",
    rental: {
      days_3_to_14: 1500000,
      more_than_14_days: 1400000,
      minimum_rental: 3,
      deposit: 25000000,
    },
    capacity: {
      passengers: 5,
      luggage: 3,
      door: 4,
    },
    features: {
      cruise_control: false,
      chassis_type: "سدان",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.6,
      cylinders: 4,
      acceleration: 11.7,
      fuel_consumption: 8.3,
    },
    with_driver: "بدون راننده",
    driver_rental: {
      hourly_10: 1900000,
      intercity_per_km: 11500,
      airport_transfer: 1250000,
    },
    img: "l90.png",
    location: "استان خراسان رضوی",
    reviewCount: 52,
    ratingNumber: 4.2,
  },
  {
    id: "peugeot-pars-1400-002",
    name: "پژو پارس",
    model: "2023-1403",
    rental: {
      days_3_to_14: 1400000,
      more_than_14_days: 1300000,
      minimum_rental: 3,
      deposit: 22000000,
    },
    capacity: {
      passengers: 5,
      luggage: 3,
      door: 4,
    },
    features: {
      cruise_control: false,
      chassis_type: "سدان",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.8,
      cylinders: 4,
      acceleration: 11.0,
      fuel_consumption: 8.5,
    },
    with_driver: "بدون راننده",
    driver_rental: {
      hourly_10: 1850000,
      intercity_per_km: 11200,
      airport_transfer: 1230000,
    },
    img: "pars.png",
    location: "استان خراسان رضوی",
    reviewCount: 50,
    ratingNumber: 4.1,
  },

  {
    id: "chery-arrizo5-1400-004",
    name: "چری آریزو ۵",
    model: "2020-1399",
    rental: {
      days_3_to_14: 1700000,
      more_than_14_days: 1600000,
      minimum_rental: 3,
      deposit: 24000000,
    },
    capacity: {
      passengers: 5,
      luggage: 3,
      door: 4,
    },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "لاکچری",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۷ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 11.0,
      fuel_consumption: 6.5,
    },
    with_driver: "بدون راننده",
    driver_rental: {
      hourly_10: 1950000,
      intercity_per_km: 11800,
      airport_transfer: 1280000,
    },
    img: "cherry-arizo-5.png",
    location: "استان البرز",
    reviewCount: 55,
    ratingNumber: 4.4,
  },
  {
    id: "kia_cerato_2018_001",
    name: "کیا سراتو",
    model: "2018-1397",
    rental: {
      days_3_to_14: 1800000,
      more_than_14_days: 1700000,
      minimum_rental: 3,
      deposit: 25000000,
    },
    capacity: {
      passengers: 5,
      luggage: 3,
      door: 4,
    },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "لاکچری",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۷ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "AUX"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 10.5,
      fuel_consumption: 7.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2100000,
      intercity_per_km: 13000,
      airport_transfer: 1450000,
    },
    img: "kia-cerato-.png",
    location: "استان اصفهان",
    reviewCount: 62,
    ratingNumber: 4.5,
  },
  {
    id: "mvm_x33_2018_002",
    name: "ام وی ام X33",
    model: "2018-1397",
    rental: {
      days_3_to_14: 1600000,
      more_than_14_days: 1500000,
      minimum_rental: 3,
      deposit: 23000000,
    },
    capacity: {
      passengers: 5,
      luggage: 4,
      door: 5,
    },
    features: {
      cruise_control: false,
      chassis_type: "کراس‌اوور",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۴ اسپیکر",
      monitor: "۷ اینچ",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["USB", "AUX"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 12.5,
      fuel_consumption: 6.9,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1950000,
      intercity_per_km: 12500,
      airport_transfer: 1380000,
    },
    img: "optima.png",
    location: "استان تهران",
    reviewCount: 58,
    ratingNumber: 4.2,
  },
  {
    id: "mitsubishi_lancer_2018_003",
    name: "میتسوبیشی لنسر",
    model: "2018-1397",
    rental: {
      days_3_to_14: 1900000,
      more_than_14_days: 1800000,
      minimum_rental: 3,
      deposit: 26000000,
    },
    capacity: {
      passengers: 5,
      luggage: 3,
      door: 4,
    },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "لاکچری",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۷ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "AUX"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.8,
      cylinders: 4,
      acceleration: 10.0,
      fuel_consumption: 7.0,
    },
    with_driver: "بدون راننده",
    driver_rental: {
      hourly_10: 2150000,
      intercity_per_km: 13500,
      airport_transfer: 1500000,
    },
    img: "hyundai-santafe.png",
    location: "استان خراسان رضوی",
    reviewCount: 64,
    ratingNumber: 4.4,
  },
  {
    id: "hyundai_elantra_2018_004",
    name: "هیوندای النترا",
    model: "2020-1399",
    rental: {
      days_3_to_14: 1850000,
      more_than_14_days: 1750000,
      minimum_rental: 3,
      deposit: 25500000,
    },
    capacity: {
      passengers: 5,
      luggage: 3,
      door: 4,
    },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "لاکچری",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "AUX"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 9.6,
      fuel_consumption: 7.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2200000,
      intercity_per_km: 14000,
      airport_transfer: 1550000,
    },
    img: "elentra.png",
    location: "استان البرز",
    reviewCount: 67,
    ratingNumber: 4.6,
  },

  {
    id: "tiba-1401-001",
    name: "تیبا ۲",
    model: "2022-1401",
    rental: {
      days_3_to_14: 1200000,
      more_than_14_days: 1100000,
      minimum_rental: 3,
      deposit: 18000000,
    },
    capacity: { passengers: 5, luggage: 2, door: 4 },
    features: {
      cruise_control: false,
      chassis_type: "هاچ‌بک",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["USB"],
      braking_system: ["ABS"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.4, cylinders: 4, acceleration: 13.5, fuel_consumption: 6.2 },
    with_driver: "بدون راننده",
    driver_rental: { hourly_10: 1600000, intercity_per_km: 10000, airport_transfer: 1100000 },
    img: "p206.png",
    location: "استان تهران",
    reviewCount: 72,
    ratingNumber: 4.0,
  },
  {
    id: "dena-plus-1402-001",
    name: "دنا پلاس",
    model: "2023-1402",
    rental: {
      days_3_to_14: 1580000,
      more_than_14_days: 1480000,
      minimum_rental: 3,
      deposit: 23500000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۴ اسپیکر",
      monitor: "۷ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.7, cylinders: 4, acceleration: 11.2, fuel_consumption: 7.0 },
    with_driver: "با راننده",
    driver_rental: { hourly_10: 1980000, intercity_per_km: 12200, airport_transfer: 1320000 },
    img: "samand-lx.png",
    location: "استان اصفهان",
    reviewCount: 61,
    ratingNumber: 4.3,
  },
  {
    id: "quick-1400-001",
    name: "کوئیک آر",
    model: "2021-1400",
    rental: {
      days_3_to_14: 1280000,
      more_than_14_days: 1180000,
      minimum_rental: 3,
      deposit: 19500000,
    },
    capacity: { passengers: 5, luggage: 2, door: 4 },
    features: {
      cruise_control: false,
      chassis_type: "هاچ‌بک",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.5, cylinders: 4, acceleration: 12.8, fuel_consumption: 6.4 },
    with_driver: "بدون راننده",
    driver_rental: { hourly_10: 1680000, intercity_per_km: 10500, airport_transfer: 1150000 },
    img: "runa.png",
    location: "استان فارس",
    reviewCount: 45,
    ratingNumber: 4.1,
  },
  {
    id: "saina-1401-001",
    name: "ساینا",
    model: "2022-1401",
    rental: {
      days_3_to_14: 1320000,
      more_than_14_days: 1220000,
      minimum_rental: 3,
      deposit: 20000000,
    },
    capacity: { passengers: 5, luggage: 2, door: 4 },
    features: {
      cruise_control: false,
      chassis_type: "سدان",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.5, cylinders: 4, acceleration: 12.5, fuel_consumption: 6.6 },
    with_driver: "بدون راننده",
    driver_rental: { hourly_10: 1720000, intercity_per_km: 10800, airport_transfer: 1180000 },
    img: "pars.png",
    location: "استان آذربایجان شرقی",
    reviewCount: 53,
    ratingNumber: 4.2,
  },
  {
    id: "kia-rio-2020-001",
    name: "کیا ریو",
    model: "2020-1399",
    rental: {
      days_3_to_14: 1750000,
      more_than_14_days: 1650000,
      minimum_rental: 3,
      deposit: 24500000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.6, cylinders: 4, acceleration: 10.8, fuel_consumption: 7.0 },
    with_driver: "با راننده",
    driver_rental: { hourly_10: 2080000, intercity_per_km: 12800, airport_transfer: 1420000 },
    img: "kia-cerato-.png",
    location: "استان خراسان رضوی",
    reviewCount: 59,
    ratingNumber: 4.5,
  },
  {
    id: "hyundai-venue-2021-001",
    name: "هیوندای ونو",
    model: "2021-1400",
    rental: {
      days_3_to_14: 1950000,
      more_than_14_days: 1850000,
      minimum_rental: 3,
      deposit: 27000000,
    },
    capacity: { passengers: 5, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی‌بلند",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.6, cylinders: 4, acceleration: 11.2, fuel_consumption: 7.2 },
    with_driver: "با راننده",
    driver_rental: { hourly_10: 2280000, intercity_per_km: 13800, airport_transfer: 1520000 },
    img: "optima.png",
    location: "استان تهران",
    reviewCount: 48,
    ratingNumber: 4.4,
  },
  {
    id: "renault-symbol-1400-001",
    name: "رنو سیمبل",
    model: "2021-1400",
    rental: {
      days_3_to_14: 1420000,
      more_than_14_days: 1320000,
      minimum_rental: 3,
      deposit: 21500000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: false,
      chassis_type: "سدان",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "۷ اینچ",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.6, cylinders: 4, acceleration: 11.5, fuel_consumption: 7.2 },
    with_driver: "بدون راننده",
    driver_rental: { hourly_10: 1780000, intercity_per_km: 11000, airport_transfer: 1220000 },
    img: "l90.png",
    location: "استان البرز",
    reviewCount: 56,
    ratingNumber: 4.2,
  },
  {
    id: "peugeot-2008-2022-001",
    name: "پژو ۲۰۰۸",
    model: "2022-1401",
    rental: {
      days_3_to_14: 2200000,
      more_than_14_days: 2050000,
      minimum_rental: 3,
      deposit: 30000000,
    },
    capacity: { passengers: 5, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی‌بلند",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۷ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.6, cylinders: 4, acceleration: 10.5, fuel_consumption: 7.5 },
    with_driver: "با راننده",
    driver_rental: { hourly_10: 2550000, intercity_per_km: 15000, airport_transfer: 1680000 },
    img: "hyundai-santafe.png",
    location: "استان اصفهان",
    reviewCount: 44,
    ratingNumber: 4.5,
  },
  {
    id: "volkswagen-polo-2019-001",
    name: "فولکس‌واگن پولو",
    model: "2019-1398",
    rental: {
      days_3_to_14: 2050000,
      more_than_14_days: 1950000,
      minimum_rental: 3,
      deposit: 28000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "هاچ‌بک",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.6, cylinders: 4, acceleration: 9.8, fuel_consumption: 6.8 },
    with_driver: "با راننده",
    driver_rental: { hourly_10: 2380000, intercity_per_km: 14200, airport_transfer: 1580000 },
    img: "elentra.png",
    location: "استان البرز",
    reviewCount: 51,
    ratingNumber: 4.6,
  },
  {
    id: "mazda3-2020-001",
    name: "مزدا ۳",
    model: "2020-1399",
    rental: {
      days_3_to_14: 1980000,
      more_than_14_days: 1880000,
      minimum_rental: 3,
      deposit: 26500000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "لاکچری",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 2.0, cylinders: 4, acceleration: 9.5, fuel_consumption: 7.2 },
    with_driver: "بدون راننده",
    driver_rental: { hourly_10: 2320000, intercity_per_km: 14000, airport_transfer: 1550000 },
    img: "cherry-arizo-5.png",
    location: "استان تهران",
    reviewCount: 66,
    ratingNumber: 4.5,
  },
  {
    id: "toyota-corolla-2019-001",
    name: "تویوتا کورولا",
    model: "2019-1398",
    rental: {
      days_3_to_14: 2400000,
      more_than_14_days: 2250000,
      minimum_rental: 3,
      deposit: 32000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.8, cylinders: 4, acceleration: 9.2, fuel_consumption: 6.5 },
    with_driver: "با راننده",
    driver_rental: { hourly_10: 2680000, intercity_per_km: 15800, airport_transfer: 1750000 },
    img: "elentra.png",
    location: "استان خراسان رضوی",
    reviewCount: 73,
    ratingNumber: 4.7,
  },
  {
    id: "honda-civic-2020-001",
    name: "هوندا سیویک",
    model: "2020-1399",
    rental: {
      days_3_to_14: 2550000,
      more_than_14_days: 2400000,
      minimum_rental: 3,
      deposit: 34000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۸ اسپیکر",
      monitor: "۷ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.8, cylinders: 4, acceleration: 8.8, fuel_consumption: 6.8 },
    with_driver: "با راننده",
    driver_rental: { hourly_10: 2850000, intercity_per_km: 16500, airport_transfer: 1850000 },
    img: "hyundai-santafe.png",
    location: "استان تهران",
    reviewCount: 58,
    ratingNumber: 4.6,
  },
  {
    id: "bmw-320-2018-001",
    name: "بی‌ام‌دبلیو سری ۳",
    model: "2018-1397",
    rental: {
      days_3_to_14: 4200000,
      more_than_14_days: 3950000,
      minimum_rental: 3,
      deposit: 55000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "لاکچری",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۸ اسپیکر",
      monitor: "۱۰ اینچ",
      driver_seat_adjustment: "برقی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 2.0, cylinders: 4, acceleration: 7.2, fuel_consumption: 7.5 },
    with_driver: "با راننده",
    driver_rental: { hourly_10: 4500000, intercity_per_km: 22000, airport_transfer: 2500000 },
    img: "elentra.png",
    location: "استان تهران",
    reviewCount: 42,
    ratingNumber: 4.8,
  },
  {
    id: "saipa-111-1400-001",
    name: "سایپا ۱۱۱",
    model: "2021-1400",
    rental: {
      days_3_to_14: 1150000,
      more_than_14_days: 1050000,
      minimum_rental: 3,
      deposit: 17000000,
    },
    capacity: { passengers: 5, luggage: 2, door: 4 },
    features: {
      cruise_control: false,
      chassis_type: "سدان",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["USB"],
      braking_system: ["ABS"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.4, cylinders: 4, acceleration: 14.0, fuel_consumption: 6.0 },
    with_driver: "بدون راننده",
    driver_rental: { hourly_10: 1520000, intercity_per_km: 9500, airport_transfer: 1050000 },
    img: "p206.png",
    location: "استان گیلان",
    reviewCount: 38,
    ratingNumber: 3.9,
  },
  {
    id: "jac-j5-1401-001",
    name: "جک J5",
    model: "2022-1401",
    rental: {
      days_3_to_14: 1650000,
      more_than_14_days: 1550000,
      minimum_rental: 3,
      deposit: 24500000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۷ اینچ",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: { type: "بنزینی", capacity: 1.5, cylinders: 4, acceleration: 11.0, fuel_consumption: 6.8 },
    with_driver: "با راننده",
    driver_rental: { hourly_10: 1980000, intercity_per_km: 12200, airport_transfer: 1350000 },
    img: "cherry-arizo-5.png",
    location: "استان یزد",
    reviewCount: 47,
    ratingNumber: 4.3,
  },
];
