import { CarsModel } from "@/models/cars.model";

type CarEntry = {
  img: string;
  name: string;
  model: string;
  rental: CarsModel["rental"];
  capacity: CarsModel["capacity"];
  features: CarsModel["features"];
  engine: CarsModel["engine"];
  with_driver: string;
  driver_rental: CarsModel["driver_rental"];
  reviewCount: number;
  ratingNumber: number;
};

/** مکان‌های پخش‌شده در سراسر ایران (۴۹ مورد برای ۴۹ خودرو) */
const CAR_LOCATIONS: string[] = [
  "استان تهران",
  "استان اصفهان",
  "استان خراسان رضوی",
  "استان البرز",
  "استان فارس",
  "استان آذربایجان شرقی",
  "استان گیلان",
  "استان یزد",
  "استان مازندران",
  "استان آذربایجان غربی",
  "استان خوزستان",
  "استان همدان",
  "استان کرمان",
  "استان کرمانشاه",
  "استان قزوین",
  "استان مرکزی",
  "استان قم",
  "استان گلستان",
  "استان زنجان",
  "استان سمنان",
  "استان کردستان",
  "استان بوشهر",
  "استان اردبیل",
  "استان لرستان",
  "استان هرمزگان",
  "استان چهارمحال و بختیاری",
  "استان ایلام",
  "استان کهگیلویه و بویراحمد",
  "استان خراسان شمالی",
  "استان خراسان جنوبی",
  "استان تهران",
  "استان اصفهان",
  "استان خراسان رضوی",
  "استان البرز",
  "استان فارس",
  "استان آذربایجان شرقی",
  "استان گیلان",
  "استان یزد",
  "استان مازندران",
  "استان آذربایجان غربی",
  "استان خوزستان",
  "استان همدان",
  "استان کرمان",
  "استان کرمانشاه",
  "استان قزوین",
  "استان مرکزی",
  "استان قم",
  "استان گلستان",
  "استان زنجان",
  "استان سمنان",
  "استان کردستان",
];

const CAR_ENTRIES: CarEntry[] = [
  {
    img: "2020-Dodge-isrental.webp",
    name: "داج اجاره‌ای",
    model: "2020",
    rental: {
      days_3_to_14: 2200000,
      more_than_14_days: 2000000,
      minimum_rental: 3,
      deposit: 35000000,
    },
    capacity: { passengers: 5, luggage: 4, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.4,
      cylinders: 4,
      acceleration: 10.5,
      fuel_consumption: 9.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2500000,
      intercity_per_km: 14000,
      airport_transfer: 1500000,
    },
    reviewCount: 28,
    ratingNumber: 4.2,
  },
  {
    img: "730li.png",
    name: "بی‌ام‌و ۷۳۰",
    model: "1401",
    rental: {
      days_3_to_14: 4500000,
      more_than_14_days: 4200000,
      minimum_rental: 3,
      deposit: 80000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "هامان کاردن",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Wireless Charging", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 6.3,
      fuel_consumption: 6.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 4500000,
      intercity_per_km: 22000,
      airport_transfer: 3500000,
    },
    reviewCount: 45,
    ratingNumber: 4.8,
  },
  {
    img: "arrizo-6.webp",
    name: "چری آریزو ۶",
    model: "1401",
    rental: {
      days_3_to_14: 1600000,
      more_than_14_days: 1500000,
      minimum_rental: 3,
      deposit: 25000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "سی‌ویتی",
      apple_carplay: true,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 9.2,
      fuel_consumption: 6.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1900000,
      intercity_per_km: 11500,
      airport_transfer: 1250000,
    },
    reviewCount: 62,
    ratingNumber: 4.3,
  },
  {
    img: "biging-x7.webp",
    name: "بیگینگ ایکس۷",
    model: "1402",
    rental: {
      days_3_to_14: 2000000,
      more_than_14_days: 1850000,
      minimum_rental: 3,
      deposit: 30000000,
    },
    capacity: { passengers: 7, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند ۷ نفره",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۲ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 9.5,
      fuel_consumption: 8.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2200000,
      intercity_per_km: 13000,
      airport_transfer: 1450000,
    },
    reviewCount: 38,
    ratingNumber: 4.4,
  },
  {
    img: "Bmw-630_.webp",
    name: "بی‌ام‌و ۶۳۰",
    model: "1401",
    rental: {
      days_3_to_14: 5000000,
      more_than_14_days: 4600000,
      minimum_rental: 3,
      deposit: 90000000,
    },
    capacity: { passengers: 4, luggage: 2, door: 2 },
    features: {
      cruise_control: true,
      chassis_type: "گرن توریسمو",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "هامان کاردن",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 5.8,
      fuel_consumption: 6.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 5000000,
      intercity_per_km: 25000,
      airport_transfer: 4000000,
    },
    reviewCount: 22,
    ratingNumber: 4.7,
  },
  {
    img: "bmw330i.png",
    name: "بی‌ام‌و ۳۳۰",
    model: "1401",
    rental: {
      days_3_to_14: 3200000,
      more_than_14_days: 3000000,
      minimum_rental: 3,
      deposit: 55000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان اسپرت",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "هامان کاردن",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 5.8,
      fuel_consumption: 6.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 3500000,
      intercity_per_km: 18000,
      airport_transfer: 2200000,
    },
    reviewCount: 55,
    ratingNumber: 4.6,
  },
  {
    img: "bmw_528.png",
    name: "بی‌ام‌و ۵۲۸",
    model: "1400",
    rental: {
      days_3_to_14: 3800000,
      more_than_14_days: 3500000,
      minimum_rental: 3,
      deposit: 65000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "هامان کاردن",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 6.2,
      fuel_consumption: 6.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 4000000,
      intercity_per_km: 20000,
      airport_transfer: 2800000,
    },
    reviewCount: 41,
    ratingNumber: 4.5,
  },
  {
    img: "c200.png",
    name: "مرسدس C200",
    model: "1401",
    rental: {
      days_3_to_14: 3500000,
      more_than_14_days: 3200000,
      minimum_rental: 3,
      deposit: 60000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان کامپکت لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "برلینر",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 7.3,
      fuel_consumption: 5.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 3800000,
      intercity_per_km: 19000,
      airport_transfer: 2500000,
    },
    reviewCount: 68,
    ratingNumber: 4.7,
  },
  {
    img: "cerato-new.webp",
    name: "کیا سيراتو (جدید)",
    model: "1402",
    rental: {
      days_3_to_14: 1950000,
      more_than_14_days: 1800000,
      minimum_rental: 3,
      deposit: 28000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 10.2,
      fuel_consumption: 7.0,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2100000,
      intercity_per_km: 12500,
      airport_transfer: 1350000,
    },
    reviewCount: 52,
    ratingNumber: 4.4,
  },
  {
    img: "dignity.webp",
    name: "ام‌وی‌ام دیگنیتی",
    model: "1401",
    rental: {
      days_3_to_14: 1700000,
      more_than_14_days: 1600000,
      minimum_rental: 3,
      deposit: 26000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "سی‌ویتی",
      apple_carplay: false,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۷ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 9.8,
      fuel_consumption: 6.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2000000,
      intercity_per_km: 12000,
      airport_transfer: 1300000,
    },
    reviewCount: 71,
    ratingNumber: 4.2,
  },
  {
    img: "e280.webp",
    name: "مرسدس E280",
    model: "1400",
    rental: {
      days_3_to_14: 4000000,
      more_than_14_days: 3700000,
      minimum_rental: 3,
      deposit: 70000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "برلینر",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 6.8,
      fuel_consumption: 6.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 4200000,
      intercity_per_km: 21000,
      airport_transfer: 3000000,
    },
    reviewCount: 35,
    ratingNumber: 4.6,
  },
  {
    img: "fownix.webp",
    name: "تویوتا فونیکس",
    model: "1402",
    rental: {
      days_3_to_14: 1800000,
      more_than_14_days: 1650000,
      minimum_rental: 3,
      deposit: 27000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "کراس اوور",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "سی‌ویتی",
      apple_carplay: true,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۹ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 11.5,
      fuel_consumption: 5.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2000000,
      intercity_per_km: 12000,
      airport_transfer: 1300000,
    },
    reviewCount: 44,
    ratingNumber: 4.3,
  },
  {
    img: "hunday-genesis.png",
    name: "هیوندای جنسیس",
    model: "1401",
    rental: {
      days_3_to_14: 4200000,
      more_than_14_days: 3900000,
      minimum_rental: 3,
      deposit: 75000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "لکسیکان",
      monitor: "۱۴.۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Wireless Charging", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.5,
      cylinders: 4,
      acceleration: 6.0,
      fuel_consumption: 7.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 4400000,
      intercity_per_km: 22000,
      airport_transfer: 3200000,
    },
    reviewCount: 29,
    ratingNumber: 4.7,
  },
  {
    img: "hyundai-santafe (1).png",
    name: "هیوندای سانتافه",
    model: "1401",
    rental: {
      days_3_to_14: 2800000,
      more_than_14_days: 2600000,
      minimum_rental: 3,
      deposit: 45000000,
    },
    capacity: { passengers: 7, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند ۷ نفره",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۸ اسپیکر",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.5,
      cylinders: 4,
      acceleration: 8.2,
      fuel_consumption: 8.0,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 3000000,
      intercity_per_km: 16000,
      airport_transfer: 1800000,
    },
    reviewCount: 58,
    ratingNumber: 4.5,
  },
  {
    img: "hyundai-santafe.png",
    name: "هیوندای سانتافه",
    model: "1402",
    rental: {
      days_3_to_14: 2900000,
      more_than_14_days: 2700000,
      minimum_rental: 3,
      deposit: 48000000,
    },
    capacity: { passengers: 7, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند ۷ نفره",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۸ اسپیکر",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.5,
      cylinders: 4,
      acceleration: 7.8,
      fuel_consumption: 7.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 3100000,
      intercity_per_km: 16500,
      airport_transfer: 1900000,
    },
    reviewCount: 42,
    ratingNumber: 4.5,
  },
  {
    img: "hyundai-sonata-yf.png",
    name: "هیوندای سوناتا YF",
    model: "1400",
    rental: {
      days_3_to_14: 2100000,
      more_than_14_days: 1950000,
      minimum_rental: 3,
      deposit: 32000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۷ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 9.5,
      fuel_consumption: 7.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2300000,
      intercity_per_km: 13500,
      airport_transfer: 1450000,
    },
    reviewCount: 66,
    ratingNumber: 4.4,
  },
  {
    img: "jacg71.webp",
    name: "جک G71",
    model: "1402",
    rental: {
      days_3_to_14: 2400000,
      more_than_14_days: 2200000,
      minimum_rental: 3,
      deposit: 38000000,
    },
    capacity: { passengers: 5, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۸ اسپیکر",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 9.0,
      fuel_consumption: 8.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2600000,
      intercity_per_km: 15000,
      airport_transfer: 1650000,
    },
    reviewCount: 33,
    ratingNumber: 4.3,
  },
  {
    img: "jack-s5.webp",
    name: "جک S5",
    model: "1401",
    rental: {
      days_3_to_14: 1750000,
      more_than_14_days: 1650000,
      minimum_rental: 3,
      deposit: 27000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند",
      option_type: "استاندارد",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۰ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 10.5,
      fuel_consumption: 7.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2000000,
      intercity_per_km: 12000,
      airport_transfer: 1300000,
    },
    reviewCount: 49,
    ratingNumber: 4.1,
  },
  {
    img: "jackj4.webp",
    name: "جک J4",
    model: "1401",
    rental: {
      days_3_to_14: 1550000,
      more_than_14_days: 1450000,
      minimum_rental: 3,
      deposit: 24000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "کراس اوور",
      option_type: "استاندارد",
      hill_start_assist: true,
      transmission: "سی‌ویتی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۰ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 11.2,
      fuel_consumption: 6.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1800000,
      intercity_per_km: 11000,
      airport_transfer: 1200000,
    },
    reviewCount: 56,
    ratingNumber: 4.2,
  },
  {
    img: "kia-cerato- (1).png",
    name: "کیا سيراتو",
    model: "1401",
    rental: {
      days_3_to_14: 1850000,
      more_than_14_days: 1720000,
      minimum_rental: 3,
      deposit: 28000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 10.0,
      fuel_consumption: 7.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2050000,
      intercity_per_km: 12200,
      airport_transfer: 1320000,
    },
    reviewCount: 61,
    ratingNumber: 4.3,
  },
  {
    img: "kia-cerato- (2).png",
    name: "کیا سيراتو",
    model: "1402",
    rental: {
      days_3_to_14: 1900000,
      more_than_14_days: 1780000,
      minimum_rental: 3,
      deposit: 28500000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 9.8,
      fuel_consumption: 7.0,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2100000,
      intercity_per_km: 12500,
      airport_transfer: 1350000,
    },
    reviewCount: 47,
    ratingNumber: 4.4,
  },
  {
    img: "kia-cerato-.png",
    name: "کیا سيراتو",
    model: "1400",
    rental: {
      days_3_to_14: 1780000,
      more_than_14_days: 1650000,
      minimum_rental: 3,
      deposit: 26500000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "استاندارد",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۷ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 10.2,
      fuel_consumption: 7.3,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1950000,
      intercity_per_km: 11800,
      airport_transfer: 1280000,
    },
    reviewCount: 73,
    ratingNumber: 4.2,
  },
  {
    img: "kia-sorento.png",
    name: "کیا سورنتو",
    model: "1401",
    rental: {
      days_3_to_14: 2600000,
      more_than_14_days: 2400000,
      minimum_rental: 3,
      deposit: 42000000,
    },
    capacity: { passengers: 7, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند ۷ نفره",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۸ اسپیکر",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.5,
      cylinders: 4,
      acceleration: 8.5,
      fuel_consumption: 8.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2800000,
      intercity_per_km: 15500,
      airport_transfer: 1700000,
    },
    reviewCount: 51,
    ratingNumber: 4.5,
  },
  {
    img: "lamari.webp",
    name: "تویوتا لندکروز لاماری",
    model: "1402",
    rental: {
      days_3_to_14: 5500000,
      more_than_14_days: 5000000,
      minimum_rental: 3,
      deposit: 95000000,
    },
    capacity: { passengers: 5, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "جی‌بی‌ال",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Wireless Charging", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 3.5,
      cylinders: 6,
      acceleration: 6.0,
      fuel_consumption: 10.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 5500000,
      intercity_per_km: 28000,
      airport_transfer: 4200000,
    },
    reviewCount: 19,
    ratingNumber: 4.8,
  },
  {
    img: "lanser.png",
    name: "میتسوبیشی لنسر",
    model: "1401",
    rental: {
      days_3_to_14: 1650000,
      more_than_14_days: 1550000,
      minimum_rental: 3,
      deposit: 25000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "سی‌ویتی",
      apple_carplay: true,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.6,
      cylinders: 4,
      acceleration: 11.2,
      fuel_consumption: 6.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1900000,
      intercity_per_km: 11500,
      airport_transfer: 1250000,
    },
    reviewCount: 64,
    ratingNumber: 4.3,
  },
  {
    img: "lexus.png",
    name: "لکسوس",
    model: "1401",
    rental: {
      days_3_to_14: 4800000,
      more_than_14_days: 4400000,
      minimum_rental: 3,
      deposit: 85000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "مارک لوینسون",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.5,
      cylinders: 4,
      acceleration: 9.2,
      fuel_consumption: 5.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 4800000,
      intercity_per_km: 24000,
      airport_transfer: 3600000,
    },
    reviewCount: 31,
    ratingNumber: 4.7,
  },
  {
    img: "lexuse-es.webp",
    name: "لکسوس ES",
    model: "1402",
    rental: {
      days_3_to_14: 5200000,
      more_than_14_days: 4800000,
      minimum_rental: 3,
      deposit: 90000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "مارک لوینسون",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.5,
      cylinders: 4,
      acceleration: 8.9,
      fuel_consumption: 5.6,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 5200000,
      intercity_per_km: 26000,
      airport_transfer: 3800000,
    },
    reviewCount: 26,
    ratingNumber: 4.8,
  },
  {
    img: "macan.png",
    name: "پورشه ماکان",
    model: "1401",
    rental: {
      days_3_to_14: 6000000,
      more_than_14_days: 5500000,
      minimum_rental: 3,
      deposit: 100000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند اسپرت",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "بوز",
      monitor: "۱۰.۹ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 6.1,
      fuel_consumption: 8.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 6000000,
      intercity_per_km: 30000,
      airport_transfer: 4500000,
    },
    reviewCount: 17,
    ratingNumber: 4.9,
  },
  {
    img: "mvm-x33.webp",
    name: "ام‌وی‌ام X33",
    model: "1402",
    rental: {
      days_3_to_14: 1580000,
      more_than_14_days: 1480000,
      minimum_rental: 3,
      deposit: 24000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "کراس اوور",
      option_type: "استاندارد",
      hill_start_assist: true,
      transmission: "سی‌ویتی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۰ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 11.0,
      fuel_consumption: 6.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1800000,
      intercity_per_km: 11000,
      airport_transfer: 1200000,
    },
    reviewCount: 53,
    ratingNumber: 4.2,
  },
  {
    img: "nx-self.webp",
    name: "لکسوس NX",
    model: "1402",
    rental: {
      days_3_to_14: 3800000,
      more_than_14_days: 3500000,
      minimum_rental: 3,
      deposit: 65000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "پایونیر",
      monitor: "۱۴ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.5,
      cylinders: 4,
      acceleration: 9.2,
      fuel_consumption: 6.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 4000000,
      intercity_per_km: 20000,
      airport_transfer: 2800000,
    },
    reviewCount: 39,
    ratingNumber: 4.6,
  },
  {
    img: "optima.png",
    name: "کیا اپتیما",
    model: "1401",
    rental: {
      days_3_to_14: 2200000,
      more_than_14_days: 2050000,
      minimum_rental: 3,
      deposit: 35000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 9.5,
      fuel_consumption: 7.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2400000,
      intercity_per_km: 14000,
      airport_transfer: 1500000,
    },
    reviewCount: 59,
    ratingNumber: 4.4,
  },
  {
    img: "p206.png",
    name: "پژو ۲۰۶",
    model: "1400",
    rental: {
      days_3_to_14: 1200000,
      more_than_14_days: 1100000,
      minimum_rental: 3,
      deposit: 18000000,
    },
    capacity: { passengers: 5, luggage: 2, door: 4 },
    features: {
      cruise_control: false,
      chassis_type: "هاچ‌بک",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["USB"],
      braking_system: ["ABS"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.4,
      cylinders: 4,
      acceleration: 13.5,
      fuel_consumption: 6.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1500000,
      intercity_per_km: 9500,
      airport_transfer: 1000000,
    },
    reviewCount: 88,
    ratingNumber: 4.0,
  },
  {
    img: "p207 (1).png",
    name: "پژو ۲۰۷",
    model: "1401",
    rental: {
      days_3_to_14: 1350000,
      more_than_14_days: 1250000,
      minimum_rental: 3,
      deposit: 20000000,
    },
    capacity: { passengers: 5, luggage: 2, door: 4 },
    features: {
      cruise_control: false,
      chassis_type: "هاچ‌بک",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.4,
      cylinders: 4,
      acceleration: 12.8,
      fuel_consumption: 6.0,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1650000,
      intercity_per_km: 10000,
      airport_transfer: 1100000,
    },
    reviewCount: 76,
    ratingNumber: 4.1,
  },
  {
    img: "p207.png",
    name: "پژو ۲۰۷",
    model: "1400",
    rental: {
      days_3_to_14: 1300000,
      more_than_14_days: 1200000,
      minimum_rental: 3,
      deposit: 19500000,
    },
    capacity: { passengers: 5, luggage: 2, door: 4 },
    features: {
      cruise_control: false,
      chassis_type: "هاچ‌بک",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.4,
      cylinders: 4,
      acceleration: 13.0,
      fuel_consumption: 6.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1600000,
      intercity_per_km: 9800,
      airport_transfer: 1050000,
    },
    reviewCount: 82,
    ratingNumber: 4.0,
  },
  {
    img: "pars.png",
    name: "پژو پارس",
    model: "1401",
    rental: {
      days_3_to_14: 1400000,
      more_than_14_days: 1300000,
      minimum_rental: 3,
      deposit: 21000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: false,
      chassis_type: "سدان",
      option_type: "استاندارد",
      hill_start_assist: false,
      transmission: "دستی",
      apple_carplay: false,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: false,
      audio_system: "۴ اسپیکر",
      monitor: "ندارد",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: false,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 1.6,
      cylinders: 4,
      acceleration: 12.0,
      fuel_consumption: 6.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1700000,
      intercity_per_km: 10500,
      airport_transfer: 1150000,
    },
    reviewCount: 69,
    ratingNumber: 4.1,
  },
  {
    img: "prado-2012.webp",
    name: "تویوتا پرادو",
    model: "2012",
    rental: {
      days_3_to_14: 3200000,
      more_than_14_days: 3000000,
      minimum_rental: 3,
      deposit: 52000000,
    },
    capacity: { passengers: 7, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند ۷ نفره",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: false,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۷ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.7,
      cylinders: 4,
      acceleration: 10.5,
      fuel_consumption: 10.0,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 3400000,
      intercity_per_km: 17500,
      airport_transfer: 2100000,
    },
    reviewCount: 43,
    ratingNumber: 4.5,
  },
  {
    img: "rental-bmw-x3.png",
    name: "بی‌ام‌و X3",
    model: "1401",
    rental: {
      days_3_to_14: 3600000,
      more_than_14_days: 3350000,
      minimum_rental: 3,
      deposit: 62000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "هامان کاردن",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 6.5,
      fuel_consumption: 7.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 3800000,
      intercity_per_km: 19500,
      airport_transfer: 2600000,
    },
    reviewCount: 37,
    ratingNumber: 4.6,
  },
  {
    img: "rental-bmw-z4.png",
    name: "بی‌ام‌و Z4",
    model: "1401",
    rental: {
      days_3_to_14: 4800000,
      more_than_14_days: 4400000,
      minimum_rental: 3,
      deposit: 85000000,
    },
    capacity: { passengers: 2, luggage: 1, door: 2 },
    features: {
      cruise_control: true,
      chassis_type: "کابریوله اسپرت",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "هامان کاردن",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 5.4,
      fuel_consumption: 6.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 5000000,
      intercity_per_km: 25000,
      airport_transfer: 3800000,
    },
    reviewCount: 14,
    ratingNumber: 4.8,
  },
  {
    img: "rental-kia-mohavi.png",
    name: "کیا موهاوی",
    model: "1401",
    rental: {
      days_3_to_14: 3000000,
      more_than_14_days: 2800000,
      minimum_rental: 3,
      deposit: 50000000,
    },
    capacity: { passengers: 7, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند ۷ نفره",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۸ اسپیکر",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.2,
      cylinders: 4,
      acceleration: 9.0,
      fuel_consumption: 8.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 3200000,
      intercity_per_km: 17000,
      airport_transfer: 1950000,
    },
    reviewCount: 34,
    ratingNumber: 4.5,
  },
  {
    img: "rental-porsche-boxter.png",
    name: "پورشه باکستر",
    model: "1401",
    rental: {
      days_3_to_14: 5500000,
      more_than_14_days: 5100000,
      minimum_rental: 3,
      deposit: 92000000,
    },
    capacity: { passengers: 2, luggage: 1, door: 2 },
    features: {
      cruise_control: true,
      chassis_type: "کابریوله اسپرت",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "بوز",
      monitor: "۷ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 5.5,
      fuel_consumption: 7.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 5500000,
      intercity_per_km: 28000,
      airport_transfer: 4000000,
    },
    reviewCount: 12,
    ratingNumber: 4.9,
  },
  {
    img: "s500.png",
    name: "مرسدس S500",
    model: "1400",
    rental: {
      days_3_to_14: 7000000,
      more_than_14_days: 6500000,
      minimum_rental: 3,
      deposit: 120000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان سوپر لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "بورمستر",
      monitor: "۱۲.۸ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Wireless Charging", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: true,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 3.0,
      cylinders: 6,
      acceleration: 4.6,
      fuel_consumption: 7.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 7000000,
      intercity_per_km: 35000,
      airport_transfer: 5000000,
    },
    reviewCount: 8,
    ratingNumber: 4.9,
  },
  {
    img: "sonatalf.webp",
    name: "هیوندای سوناتا LF",
    model: "1401",
    rental: {
      days_3_to_14: 2300000,
      more_than_14_days: 2150000,
      minimum_rental: 3,
      deposit: 36000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 4 },
    features: {
      cruise_control: true,
      chassis_type: "سدان",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۸ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 9.2,
      fuel_consumption: 7.0,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2500000,
      intercity_per_km: 14500,
      airport_transfer: 1550000,
    },
    reviewCount: 54,
    ratingNumber: 4.4,
  },
  {
    img: "sportage.png",
    name: "کیا اسپورتیج",
    model: "1401",
    rental: {
      days_3_to_14: 2500000,
      more_than_14_days: 2320000,
      minimum_rental: 3,
      deposit: 40000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 8.5,
      fuel_consumption: 7.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2700000,
      intercity_per_km: 15200,
      airport_transfer: 1650000,
    },
    reviewCount: 48,
    ratingNumber: 4.5,
  },
  {
    img: "tiggo-7-poro.webp",
    name: "چری تیگو ۷ پرو",
    model: "1402",
    rental: {
      days_3_to_14: 1880000,
      more_than_14_days: 1750000,
      minimum_rental: 3,
      deposit: 29000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "سی‌ویتی",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 9.8,
      fuel_consumption: 7.0,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2100000,
      intercity_per_km: 12500,
      airport_transfer: 1350000,
    },
    reviewCount: 46,
    ratingNumber: 4.3,
  },
  {
    img: "tiggo-8-pro-max.webp",
    name: "چری تیگو ۸ پرو مکس",
    model: "1402",
    rental: {
      days_3_to_14: 2150000,
      more_than_14_days: 2000000,
      minimum_rental: 3,
      deposit: 34000000,
    },
    capacity: { passengers: 7, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند ۷ نفره",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۸ اسپیکر",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 1.6,
      cylinders: 4,
      acceleration: 9.5,
      fuel_consumption: 7.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2350000,
      intercity_per_km: 13800,
      airport_transfer: 1500000,
    },
    reviewCount: 36,
    ratingNumber: 4.4,
  },
  {
    img: "tiggo7.webp",
    name: "چری تیگو ۷",
    model: "1401",
    rental: {
      days_3_to_14: 1720000,
      more_than_14_days: 1620000,
      minimum_rental: 3,
      deposit: 26500000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند",
      option_type: "استاندارد",
      hill_start_assist: true,
      transmission: "سی‌ویتی",
      apple_carplay: true,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۰ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 10.2,
      fuel_consumption: 7.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1950000,
      intercity_per_km: 11800,
      airport_transfer: 1280000,
    },
    reviewCount: 58,
    ratingNumber: 4.2,
  },
  {
    img: "tusan.png",
    name: "تویوتا توسان",
    model: "1401",
    rental: {
      days_3_to_14: 2450000,
      more_than_14_days: 2280000,
      minimum_rental: 3,
      deposit: 38000000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "کراس اوور",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۰.۱ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 10.5,
      fuel_consumption: 7.2,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 2650000,
      intercity_per_km: 15000,
      airport_transfer: 1620000,
    },
    reviewCount: 63,
    ratingNumber: 4.4,
  },
  {
    img: "x5.webp",
    name: "بی‌ام‌و X5",
    model: "1401",
    rental: {
      days_3_to_14: 4200000,
      more_than_14_days: 3900000,
      minimum_rental: 3,
      deposit: 72000000,
    },
    capacity: { passengers: 5, luggage: 4, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "شاسی بلند لوکس",
      option_type: "فول آپشن",
      hill_start_assist: true,
      transmission: "اتوماتیک",
      apple_carplay: true,
      seat_heating: true,
      seat_cooling: true,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "هامان کاردن",
      monitor: "۱۲.۳ اینچی لمسی",
      driver_seat_adjustment: "الکتریکی",
      panoramic_roof: true,
      gps: true,
      connectivity: ["Bluetooth", "USB", "Apple CarPlay"],
      braking_system: ["ABS", "EBD", "ESP"],
      auto_park: true,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 2.0,
      cylinders: 4,
      acceleration: 6.5,
      fuel_consumption: 7.5,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 4400000,
      intercity_per_km: 22000,
      airport_transfer: 3200000,
    },
    reviewCount: 24,
    ratingNumber: 4.7,
  },
  {
    img: "x55.png",
    name: "چری ایکس۵۵",
    model: "1402",
    rental: {
      days_3_to_14: 1680000,
      more_than_14_days: 1580000,
      minimum_rental: 3,
      deposit: 25500000,
    },
    capacity: { passengers: 5, luggage: 3, door: 5 },
    features: {
      cruise_control: true,
      chassis_type: "کراس اوور",
      option_type: "استاندارد",
      hill_start_assist: true,
      transmission: "سی‌ویتی",
      apple_carplay: true,
      seat_heating: false,
      seat_cooling: false,
      air_conditioning: true,
      rear_sensor: true,
      audio_system: "۶ اسپیکر",
      monitor: "۱۰.۲۵ اینچی لمسی",
      driver_seat_adjustment: "دستی",
      panoramic_roof: false,
      gps: true,
      connectivity: ["Bluetooth", "USB"],
      braking_system: ["ABS", "EBD"],
      auto_park: false,
      auto_drive: false,
    },
    engine: {
      type: "بنزینی توربو",
      capacity: 1.5,
      cylinders: 4,
      acceleration: 10.5,
      fuel_consumption: 6.8,
    },
    with_driver: "با راننده",
    driver_rental: {
      hourly_10: 1900000,
      intercity_per_km: 11500,
      airport_transfer: 1250000,
    },
    reviewCount: 41,
    ratingNumber: 4.3,
  },
];

function slugFromImg(img: string): string {
  return img
    .replace(/\s+/g, "-")
    .replace(/[().]/g, "")
    .replace(/\.[a-z0-9]+$/i, "")
    .toLowerCase();
}

function buildCar(entry: CarEntry, index: number): CarsModel {
  return {
    id: `${slugFromImg(entry.img)}-${index + 1}`,
    name: entry.name,
    model: entry.model,
    rental: entry.rental,
    capacity: entry.capacity,
    features: entry.features,
    engine: entry.engine,
    with_driver: entry.with_driver,
    driver_rental: entry.driver_rental,
    img: entry.img,
    location: CAR_LOCATIONS[index] ?? "استان تهران",
    reviewCount: entry.reviewCount,
    ratingNumber: entry.ratingNumber,
  };
}

export const cars: CarsModel[] = CAR_ENTRIES.map(buildCar);
